version: "3"
services:
  api:
    build: .devcontainer/server
    ports:
      - 8085:8085
    volumes:
      - ./:/home/vscode/daily_dos
    network_mode: 'host'
    command: bash -c "dotnet run --project
      /home/vscode/daily_dos/api/DailyDos.Api.fsproj"

  vue_client:
    build: .devcontainer/vue_client
    ports:
      - 8080:8080
    volumes:
      - ./:/home/vscode/daily_dos
    network_mode: 'host'
    command: bash -c "cd /home/vscode/daily_dos/vue_client && pnpm run serve"

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dailydos
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data: null
