version: "3"
services:
  api:
    build: server
    working_dir: /app/api
    ports:
      - 8085:8085
    volumes:
      - ../:/app
    command: dotnet watch run -p DailyDos.Api.fsproj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  vue_client:
    build: vue_client
    user: "node"
    working_dir: /home/node/app/vue_client
    ports:
      - 8080:8080
    volumes:
      - ../:/home/node/app
    command: "npm run serve"

  swagger_ui:
    image: swaggerapi/swagger-ui
    ports:
      - 9000:8080
    volumes:
      - ./swagger:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml

  swagger_editor:
    image: swaggerapi/swagger-editor
    ports:
      - 9001:8080
