version: "3"
services:
  api:
    build: server
    working_dir: /app
    ports:
      - 8085:8085
    volumes:
      - ../api:/app
    command: dotnet watch run
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - dailydos_network

  client:
    build: vue_client
    user: "node"
    working_dir: /home/node/app/vue_client
    ports:
      - 8089:5173
    volumes:
      - ../:/home/node/app
    command: "npm run dev"
    networks:
      - dailydos_network

  swagger_ui:
    image: swaggerapi/swagger-ui
    ports:
      - 9000:8080
    volumes:
      - ./swagger:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml
    networks:
      - dailydos_network

  swagger_editor:
    image: swaggerapi/swagger-editor
    ports:
      - 9001:8080
    networks:
      - dailydos_network

networks:
  dailydos_network:
