name: Build (Client)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        working-directory: ./vue_client

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Compile
        run: pnpm run build
      - name: Run linter
        run: pnpm run lint
